version: '2'
services:
    ninjaskins-postgresql:
        container_name: ninjaskins-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/ninjaskins/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=ninjaskins
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
